### ISSUE TITLE
Sound notification?

### ISSUE THREAD

**Issue by skywatcher77** [s4my/TwitchLiveChannels#1]
I love the addon, my only request is for a sound notication if its possible? Cheers

**Comment by s4my** [comment]
> I love the addon, my only request is for a sound notication if its possible? Cheers

Hi [skywatcher77](https://github.com/skywatcher77), am glad you love the add-on and cheers to you too mate 😉 , to answer your question or rather your request, Firefox notification system doesn't notify you with audio, only visually by design, most people find it annoying to have sound notifications, so I would have to play a custom sound myself. 
I'll leave this issue open if enough people request it, I might just add it. and thank you again for the feedback.

**Comment by skywatcher77** [comment]
Thanks for the quick reply. I totally understand the non-need for a sound notification, i don't have a sound for anything else in Firefox. It's handy having discord pings for when streamers go live and i happen to be looking away from the screen etc. I can also see the issue of following loads of streamers and the sound would be going off quite a lot. The annoying thing with twitch, is if im watching a streamer and another streamer i follow comes on, theres just a small notification for it at the top right which is often hard to see with multiple monitors. Your addon has at least given a better visual notification on the main monitor.

**Comment by ghost** [comment]
@s4my a bit unrelated but of all 5 addons I've tried this one is the best and actually works and does the job. The interface looks good too. This addon needs more recognition! Well done.

**Comment by s4my** [comment]
> @s4my a bit unrelated but of all 5 addons I've tried this one is the best and actually works and does the job. The interface looks good too. This addon needs more recognition! Well done.

thank you so much [r00ster91](https://github.com/r00ster91), you should leave this review on the [addons website](https://addons.mozilla.org/en-US/firefox/addon/twitch-live-channels/reviews/) and share it with whoever you can 😄 👍🏻
