### ISSUE TITLE
not updating

### ISSUE THREAD

**Issue by pkoa** [s4my/TwitchLiveChannels#2]
Stuck on yesterdays livestreams, nothing happens when clicking on update. 

![imgur](https://i.imgur.com/TfYyVFm.png)

and also the ratios are a bit weird when its in the sidebar.

![imgur](https://i.imgur.com/0tzevoF.png)

**Comment by pkoa** [comment]
now its updating as normal

**Comment by s4my** [comment]
Thank you, this might not be your intention but this showed me how broken the UI is when the extension is pinned to the Overflow Menu, which i fixed in this commit 5539ee9052625ee9fc616e9e94de477b0776f19c (patched in version <a href="https://github.com/s4my/TwitchLiveChannels/releases/tag/v1.0.9">1.0.9</a>).
