### ISSUE TITLE
Request to add two options

### ISSUE THREAD

**Issue by Arkadiusz-87** [s4my/TwitchLiveChannels#3]
Hello 
I have a request for two features in yours addon.
1. possibility to extend vertically the window with list of strims
2. possibility to display list of strims in two columns

Greetings

I use an automatic translation service, sorry for grammatical errors.

**Comment by s4my** [comment]
Hi [Arkadiusz-87](https://github.com/Arkadiusz-87), don't worry about the translation errors it's all good 😄. to answer your requests, for the 1st one: 
> 1. possibility to extend vertically the window with list of strims

It's out of my control the browser (Firefox) has control over the height, so i can't it extend any further.
For the 2nd one:
> 2. possibility to display list of strims in two columns

Here what you're asking for is more like a design overhaul rather than a feature, which i don't agree with sadly, but i appreciate the feedback never the less, and thank you for your time.
