### ISSUE TITLE
Question! What was the reason for the new permission?

### ISSUE THREAD

**Issue by Godiesc** [s4my/TwitchLiveChannels#9]
Are you going to change the twitch site on some way or why you want access to twitch user sensitive information? The twitch API changed?

![imagen](https://github.com/s4my/TwitchLiveChannels/assets/22057609/6e37311a-5d15-4188-8e8a-76fcdc2280b3)

PD: Great extension, I recommended to some users and this change worries me.

**Comment by s4my** [comment]
Hi @Godiesc, I'm glad you like it. And don't worry, I'll answer your question. A user reported an issue #8, which turned out to be a caching issue, so I had to add an extra header to my fetch requests to disable caching, ["Cache-Control"](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control), and you can't do that without triggering a Content-Security-Policy error, i.e.:
```js
Access to fetch at 'https://api.twitch.tv/helix/streams/followed?first=100&user_id=123144592' from origin 'chrome-extension://nldegckafamehhfffhcelpbbbepggdam' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

 So to fix that, you have to add the twitch domain to the permissions in the manifest, which I did in this [commit](https://github.com/s4my/TwitchLiveChannels/commit/5304e55983cbe06f9d94388b5787c90369f98ec1#diff-ffa5b716b5a57837f7929dfcca4b4dfdeb97210a7fd5a12d2f1978846d6f1743R27).

**Comment by Godiesc** [comment]
I understand, thanks for your answer, I've never have any issue with the extension so I was surprise with the latest change. Keep the good work, thanks for develop this extension.

**Comment by s4my** [comment]
You're welcome, have a nice day.
